# Generated by Django 4.1 on 2024-01-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0006_tbl_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('loginId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('licenseno', models.BigIntegerField()),
                ('contactno', models.BigIntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_district')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_login')),
            ],
        ),
    ]
