# Generated by Django 4.1 on 2024-01-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0002_rename_email_tbl_owner_owneremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_owner',
            old_name='owneremail',
            new_name='email',
        ),
    ]
