# Generated by Django 4.1 on 2024-01-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_rename_owneremail_tbl_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_owner',
            name='districtid',
        ),
    ]
