# Generated by Django 4.1 on 2024-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('requeststatus', models.CharField(max_length=100)),
                ('requestremark', models.CharField(max_length=100)),
                ('persons', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('totalamount', models.BigIntegerField()),
            ],
        ),
    ]
