# Generated by Django 4.1 on 2024-02-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0005_tbl_customer'),
        ('Customerapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentamount', models.BigIntegerField()),
                ('paymentstatus', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_customer')),
                ('requestid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customerapp.tbl_request')),
            ],
        ),
    ]
