# Generated by Django 4.1 on 2024-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0003_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='adminamount',
            field=models.BigIntegerField(null=True),
        ),
    ]
