# Generated by Django 4.1 on 2024-01-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='tbl_location',
        ),
    ]
