from django.urls import path
from Adminapp import views
from Adminapp.views import ExportExcelcustomer, ExportExcelDatewiseReport, ExportExcelowner, \
    ExportExceldistrict, ExportExcelpayment

urlpatterns = [
    path('', views.adminhome),
    path('district/', views.district, name="district"),
    path('location/', views.location, name="location"),
    path('districtview/', views.districtview, name='districtview'),
    path('districtedit/<id>/', views.editdistrict, name='districtedit'),
    path('districtdelete/<id>/', views.deletedistrict, name='districtdelete'),
    path('locationview/', views.viewlocation, name='locationview'),
    path('locationedit/<id>/', views.editlocation, name='locationedit'),
    path('locationdelete/<id>/', views.deletelocation, name='locationdelete'),
    path('filllocation',views.filllocation,name='filllocation'),
    path('category/', views.category, name='category'),
    path('viewcategory/', views.viewcategory, name='viewcategory'),
    path('editcategory/<id>/', views.editcategory, name='editcategory'),
    path('deletecategory/<id>/', views.deletecategory, name='deletecategory'),
    path('package/', views.package, name='package'),
    path('viewpackage/', views.viewpackage, name='viewpackage'),
    path('editpackage/<id>/', views.editpackage, name='editpackage'),
    path('deletepackage/<id>/', views.deletepackage, name='deletepackage'),
    path('service/', views.service, name='service'),
    path('viewservice/', views.viewservice, name='viewservice'),
    path('editservice/<id>/', views.editservice, name='editservice'),
    path('deleteservice/<id>/', views.deleteservice, name='deleteservice'),
    path('Requestbyowners/', views.Requestbyowners, name='Requestbyowners'),
    path('verify/<id>', views.verify, name='verify'),
    path('reject/<id>', views.reject, name='reject'),
    path('viewacceptedowners/', views.viewacceptedowners, name='viewacceptedowners'),
    path('rejected/<id>', views.rejected, name='rejected'),
    path('viewpayment', views.viewpayment, name='viewpayment'),
    path('logout/', views.logout, name='logout'),
    path('categorypiechart/', views.categorypiechart, name='categorypiechart'),
    path('boatpiechart/', views.boatpiechart, name='boatpiechart'),
    path('ExportExcelcustomer/', ExportExcelcustomer.as_view(), name='ExportExcelcustomer'),
    path('Exportcustomerview/', views.Exportcustomerview, name='Exportcustomerview'),
    path('ExportExcelowner/', ExportExcelowner.as_view(), name='ExportExcelowner'),
    path('Exportownerview/', views.Exportownerview, name='Exportownerview'),
    path('ExportExcelDatewiseReport/', ExportExcelDatewiseReport.as_view(), name='ExportExcelDatewiseReport'),
    path('export_excel5/', ExportExceldistrict.as_view(), name='export_excel5'),
    path('ExportExcelpayment/', ExportExcelpayment.as_view(), name='ExportExcelpayment'),
    path('Exportpaymentview/', views.Exportpaymentview, name='Exportpaymentview'),
]
